name: CI
on:
  - push
  - pull_request
jobs:
  ci:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to gh-pages
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: .
